apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-0
  labels:
    type: local
    app: elasticsearch
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/elasticsearch-master-0"
